# Generated by Django 5.2.7 on 2025-10-23 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_des_presences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_des_presences.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_des_presences.etudiant')),
            ],
            options={
                'unique_together': {('etudiant', 'cours')},
            },
        ),
    ]
