# Generated by Django 5.2.6 on 2025-10-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_des_presences', '0002_classe_semestre_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
    ]
