# Generated by Django 5.2.6 on 2025-10-01 11:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_des_presences', '0003_alter_utilisateur_nom_alter_utilisateur_prenom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anneer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('annee', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
            ],
        ),
        migrations.RemoveField(
            model_name='parent',
            name='etudiants',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='etudiants',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='horaire',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='salle',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='annee_inscription',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='Parents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_des_presences.parent'),
        ),
        migrations.AddField(
            model_name='parent',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='parent',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='presence',
            name='Cours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_des_presences.cours'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='Anneer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_des_presences.anneer'),
        ),
        migrations.DeleteModel(
            name='LienParentEtudiant',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
