# Generated by Django 5.1.5 on 2025-10-09 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_des_presences', '0004_anneer_remove_parent_etudiants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='Anneer',
            new_name='annee',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='Parents',
            new_name='parents',
        ),
        migrations.CreateModel(
            name='Sceance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cours', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_des_presences.enseignant')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_des_presences.etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='presence',
            name='sceance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_des_presences.sceance'),
        ),
    ]
