from django.urls import path
from . import views
urlpatterns = [
    path('', views.accueil, name='accueil'),
    path('etudiants/', views.liste_etudiants, name='liste_etudiants'),
    path('etudiants/ajouter/', views.etudiant_create, name='etudiant_create'),
    path('etudiants/<int:pk>/modifier/', views.etudiant_update, name='etudiant_update'),
    path('etudiants/<int:pk>/supprimer/', views.etudiant_delete, name='etudiant_delete'),
    path('enseignants/', views.liste_enseignants, name='liste_enseignants'),
    path('enseignants/ajouter/', views.enseignant_create, name='enseignant_create'),
    path('enseignants/<int:pk>/modifier/', views.enseignant_update, name='enseignant_update'),
    path('enseignants/<int:pk>/supprimer/', views.enseignant_delete, name='enseignant_delete'),
    path('cours/', views.liste_cours, name='liste_cours'),
    path('cours/ajouter/', views.cours_create, name='cours_create'),
    path('cours/<int:pk>/modifier/', views.cours_update, name='cours_update'),
    path('cours/<int:pk>/supprimer/', views.cours_delete, name='cours_delete'),
    path('annees/', views.annees_list, name='liste_annees'),
    path('annees/ajouter-form/', views.annee_create_form, name='annee_create_form'),
    path('annees/<int:pk>/modifier-form/', views.annee_update_form, name='annee_update_form'),
    path('annees/<int:pk>/supprimer-form/', views.annee_delete_form, name='annee_delete_form'),
    path('annees/create/', views.annees_create, name='annees_create'),
    path('annees/<int:pk>/update/', views.annees_update, name='annees_update'),
    path('annees/<int:pk>/delete/', views.annees_delete, name='annees_delete'),
    path('annees/ajouter/', views.ajouter_annee, name='ajouter_annee'),
]
